Key Value mapper implementation and site
wso2-extensions/siddhi-map-keyvalue pull request #1
Opened 2017-09-15 08:38 UTC by chamathabeysinghe

2017-09-15 09:12 UTC, nirmal070125 commented on README.md
> +which is used to convert Key-Value map message to/from Siddhi events.
convert and from doesn't go together. Please rephrase.

2017-09-15 09:43 UTC, dilini-muthumala requested changes

2017-09-15 09:43 UTC, dilini-muthumala commented on checkstyle-suppressions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please fix the check style issues and remove this file.

2017-09-15 09:43 UTC, dilini-muthumala commented on component/src/main/java/org/wso2/extension/siddhi/map/keyvalue/sinkmapper/KeyValueSinkMapper.java
> +
Please remove unnecessary line breaks.

2017-09-15 09:43 UTC, dilini-muthumala commented on component/src/test/java/org/wso2/extension/siddhi/map/keyvalue/sinkmapper/KeyValueSinkMapperTestCase.java
> +                        AssertJUnit.fail();
During the code review, it was suggested to specify the reason for the Assertion failure. Could you please fix it?

2017-09-15 09:43 UTC, dilini-muthumala commented on findbugs-exclude.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file.

2017-09-15 09:43 UTC, dilini-muthumala commented on pom.xml
> +        <mavan.checkstyle.suppression.file>checkstyle-suppressions.xml</mavan.checkstyle.suppression.file>
Please remove these

2017-09-18 06:06 UTC, dilini-muthumala approved these changes

2017-09-18 06:10 UTC, merged