Removed unwanted emoji from the doc
wso2-extensions/siddhi-map-keyvalue pull request #33
Opened 2019-08-21 05:44 UTC by Amstrom

## Purpose
Remove  'A' emoji that was in the Example 3 and fix some alignments.

## Goals
Removed  'A' emoji that was in the Example 3 and fixed the alignments.

## Documentation
N/A

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

2019-08-21 05:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/siddhi-io/siddhi-map-keyvalue?pullRequest=33) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/siddhi-io/siddhi-map-keyvalue?pullRequest=33) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/siddhi-io/siddhi-map-keyvalue?pullRequest=33) it.</sub>

2019-08-21 05:53 UTC, niveathika commented
@Amstrom the files under docs folder are auto-generated at release time. Update the description on @Extension annotation in the relevant class to make this cane persistent,

2019-09-09 07:22 UTC, mohanvive commented
@sahandilshan Can you please incorporate the suggestion and send those changes

2019-09-25 09:01 UTC, mohanvive requested changes

2019-09-25 09:01 UTC, mohanvive commented on docs/api/2.0.4-SNAPSHOT.md
> +# API Docs - v2.0.4-SNAPSHOT
Remove this file

2019-09-25 09:01 UTC, mohanvive commented on mkdocs.yml
> +      - 2.0.4-SNAPSHOT: api/2.0.4-SNAPSHOT.md
Remove this entry.

2019-09-25 11:41 UTC, mohanvive approved these changes

2019-09-25 11:41 UTC, merged